# Generated by Django 5.2.7 on 2025-11-06 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Marque se o material está ativo. Desmarque para exclusão lógica.', verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('name', models.CharField(help_text='Nome comercial ou designação do material (ex. Gala, Fuji, M5).', max_length=255, verbose_name='Nome / Designação')),
                ('material_type', models.CharField(choices=[('CULTIVAR', 'Cultivar'), ('SELECTION', 'Seleção'), ('HYBRID', 'Híbrido')], max_length=10, verbose_name='Tipo de Material')),
                ('internal_code', models.CharField(blank=True, editable=False, help_text='Código sequencial gerado para linhagens e cultivares (ex: L1, C5).', max_length=50, null=True, unique=True, verbose_name='Código Interno')),
                ('accession_code', models.CharField(blank=True, editable=False, help_text='Código gerado para Híbridos e mantido em suas evoluções (ex. C1xL5A25H1).', max_length=100, null=True, unique=True, verbose_name='Código de Acesso (Híbrido)')),
                ('phenology_notes', models.TextField(blank=True, help_text='Datas de brotação, floração, colheita, etc.', verbose_name='Observações de Fenologia')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='germoplasm.geneticmaterial', verbose_name='Parentais')),
            ],
            options={
                'verbose_name': 'Material Genético',
                'verbose_name_plural': 'Materiais Genéticos (BAG)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Marque se o material está ativo. Desmarque para exclusão lógica.', verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('code', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Código da População')),
                ('cross_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Cruzamento')),
                ('parent1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_parent1', to='germoplasm.geneticmaterial', verbose_name='Parental 1')),
                ('parent2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_parent2', to='germoplasm.geneticmaterial', verbose_name='Parental 2')),
            ],
            options={
                'verbose_name': 'População',
                'verbose_name_plural': 'Populações',
                'ordering': ['-cross_date'],
            },
        ),
        migrations.AddField(
            model_name='geneticmaterial',
            name='population',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hybrids', to='germoplasm.population', verbose_name='População de Origem'),
        ),
        migrations.CreateModel(
            name='DiseaseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Marque se o material está ativo. Desmarque para exclusão lógica.', verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('disease_name', models.CharField(max_length=255, verbose_name='Nome da Doença')),
                ('reaction', models.CharField(blank=True, choices=[('R', 'Resistente'), ('MR', 'Moderadamente Resistente'), ('MS', 'Moderadamente Suscetível'), ('S', 'Suscetível')], max_length=2, verbose_name='Reação')),
                ('genetic_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reactions', to='germoplasm.geneticmaterial', verbose_name='Material Genético')),
            ],
            options={
                'verbose_name': 'Reação a Doença',
                'verbose_name_plural': 'Reações a Doenças',
                'constraints': [models.UniqueConstraint(fields=('genetic_material', 'disease_name'), name='unique_reaction_per_material_disease')],
            },
        ),
    ]
