# Generated by Django 5.2.7 on 2025-11-06 20:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Local')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='PhenologicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Evento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Evento Fenológico',
                'verbose_name_plural': 'Eventos Fenológicos',
            },
        ),
        migrations.RemoveField(
            model_name='geneticmaterial',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='geneticmaterial',
            name='phenology_notes',
        ),
        migrations.AddField(
            model_name='geneticmaterial',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='germoplasm.geneticmaterial', verbose_name='Parental (Pai)'),
        ),
        migrations.AddField(
            model_name='geneticmaterial',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='germoplasm.geneticmaterial', verbose_name='Parental (Mãe)'),
        ),
        migrations.AddField(
            model_name='population',
            name='seedling_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Número total de seedlings gerados nesta população.', verbose_name='Quantidade de Seedlings'),
        ),
        migrations.AlterField(
            model_name='geneticmaterial',
            name='population',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_hybrids', to='germoplasm.population', verbose_name='População de Origem'),
        ),
        migrations.AlterField(
            model_name='population',
            name='parent1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_as_parent1', to='germoplasm.geneticmaterial', verbose_name='Parental 1'),
        ),
        migrations.AlterField(
            model_name='population',
            name='parent2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_as_parent2', to='germoplasm.geneticmaterial', verbose_name='Parental 2'),
        ),
        migrations.CreateModel(
            name='PhenologyObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Marque se o material está ativo. Desmarque para exclusão lógica.', verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('observation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Observação')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='germoplasm.phenologicalevent', verbose_name='Evento Fenológico')),
                ('genetic_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenology_observations', to='germoplasm.geneticmaterial', verbose_name='Material Genético')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='germoplasm.location', verbose_name='Local da Observação')),
            ],
            options={
                'verbose_name': 'Observação Fenológica',
                'verbose_name_plural': 'Observações Fenológicas',
                'ordering': ['-observation_date'],
            },
        ),
    ]
