# Generated by Django 5.2.7 on 2025-11-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0002_location_phenologicalevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticmaterial',
            name='mutated_from',
            field=models.ForeignKey(blank=True, help_text='Selecione o material genético original se este for uma mutação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations', to='germoplasm.geneticmaterial', verbose_name='Mudatão de'),
        ),
    ]
