# Generated by Django 5.2.7 on 2025-11-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0003_geneticmaterial_mutated_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticmaterial',
            name='is_epagri_material',
            field=models.BooleanField(default=False, help_text='Marque esta opção se o material foi gerado a partir de uma população do programa de melhoramento genético da EPAGRI.', verbose_name='É material do programa da Epagri?'),
        ),
    ]
