# Generated by Django 5.2.7 on 2025-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0004_geneticmaterial_is_epagri_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='seplan_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Códio do projeto no Seplan'),
        ),
    ]
