# Generated by Django 5.2.7 on 2025-11-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0005_population_seplan_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='seedling_quantity',
        ),
        migrations.AddField(
            model_name='population',
            name='field_seedling_quantity',
            field=models.PositiveBigIntegerField(default=0, help_text='Número total de seedlings que foram transplantados a campo', verbose_name='Quantidade de seedlings a campo'),
        ),
        migrations.AddField(
            model_name='population',
            name='flowers_quantity',
            field=models.PositiveBigIntegerField(default=0, help_text='Número total de flores emasculadas e polinizadas para esta população.', verbose_name='Quantidade de flores polinizadas'),
        ),
        migrations.AddField(
            model_name='population',
            name='fruit_quantity',
            field=models.PositiveBigIntegerField(default=0, help_text='Número total de frutos gerados a partir das flores polinizadas.', verbose_name='Quantidade de frutos gerados'),
        ),
        migrations.AddField(
            model_name='population',
            name='greenhouse_seedling_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Número total de seedlings gerados nesta população.', verbose_name='Quantidade de Seedlings na estufa'),
        ),
        migrations.AddField(
            model_name='population',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='population',
            name='seed_quantity',
            field=models.PositiveBigIntegerField(default=0, help_text='Número total de sementes coletadas a partir dos frutos obtidos no cruzamento', verbose_name='Quantidade de sementes coletadas'),
        ),
    ]
