# Generated by Django 5.2.7 on 2025-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0006_remove_population_seedling_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticmaterial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Imagem representativa do material genético.', null=True, upload_to='genetic_material_photos/', verbose_name='Foto do material'),
        ),
    ]
