# Generated by Django 5.2.7 on 2025-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0007_geneticmaterial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticmaterial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Imagem representativa do material genético.', null=True, upload_to='genetic_material_photo_path', verbose_name='Foto do material'),
        ),
    ]
