# Generated by Django 5.2.7 on 2025-11-19 19:27

import django.db.models.deletion
import germoplasm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0008_alter_geneticmaterial_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geneticmaterial',
            name='photo',
        ),
        migrations.CreateModel(
            name='GeneticMaterialPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Marque se o material está ativo. Desmarque para exclusão lógica.', verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('image', models.ImageField(upload_to=germoplasm.models.genetic_material_photo_path, verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, help_text="Descrição opcional da foto (ex: 'Fruto em ponto de colheita').", max_length=255, verbose_name='Legenda')),
                ('genetic_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='germoplasm.geneticmaterial', verbose_name='Material Genético')),
            ],
            options={
                'verbose_name': 'Foto de Material Genético',
                'verbose_name_plural': 'Fotos de Materiais Genéticos',
            },
        ),
    ]
