# Generated by Django 5.2.7 on 2025-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0009_remove_geneticmaterial_photo_geneticmaterialphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticmaterial',
            name='Observações',
            field=models.TextField(blank=True, help_text='Utilize este campo se necessário para adicionar informações uteis sobre o genótipo.'),
        ),
    ]
