# Generated by Django 5.2.7 on 2025-12-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0010_geneticmaterial_observações'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geneticmaterial',
            name='Observações',
        ),
        migrations.AddField(
            model_name='geneticmaterial',
            name='observations',
            field=models.TextField(blank=True, help_text='Utilize este campo se necessário para adicionar informações uteis sobre o genótipo.', verbose_name='Observações'),
        ),
    ]
