# Generated by Django 5.2.7 on 2025-12-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0011_remove_geneticmaterial_observações_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Marque se o material está ativo. Desmarque para exclusão lógica.', verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Marcador')),
                ('marker_type', models.CharField(choices=[('SSR', 'SSR (Microssatélite)'), ('SNP', 'SNP'), ('CAPS', 'CAPS'), ('OTHER', 'Outro')], max_length=10, verbose_name='Tipo de Marcador')),
                ('primer_forward', models.CharField(blank=True, max_length=100, verbose_name='Primer Forward')),
                ('primer_reverse', models.CharField(blank=True, max_length=100, verbose_name='Primer Reverse')),
                ('pcr_protocol', models.TextField(blank=True, verbose_name='Protocolo de PCR')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S_Allele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Marque se o material está ativo. Desmarque para exclusão lógica.', verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('name', models.CharField(help_text='Ex: S1, S2, S3, S9', max_length=50, unique=True, verbose_name='Nome do Alelo S')),
                ('markers', models.ManyToManyField(blank=True, related_name='s_alleles', to='germoplasm.marker', verbose_name='Marcadores para Identificação')),
            ],
            options={
                'verbose_name': 'Alelo S',
                'verbose_name_plural': 'Alelos S',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='geneticmaterial',
            name='s_alleles',
            field=models.ManyToManyField(blank=True, help_text='Selecione os alelos S que compõem o genótipo deste material', related_name='genetic_materials', to='germoplasm.s_allele', verbose_name='Genótipo S (Alelos S)'),
        ),
    ]
