# Generated by Django 5.2.7 on 2025-12-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0012_marker_s_allele_geneticmaterial_s_alleles'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticmaterial',
            name='ifo_discarded',
            field=models.BooleanField(default=False, help_text='Marque se o material foi descartado durante o processo na IFO.', verbose_name='Descarte no IFO'),
        ),
        migrations.AddField(
            model_name='geneticmaterial',
            name='ifo_discarded_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Descarte no IFO'),
        ),
        migrations.AddField(
            model_name='geneticmaterial',
            name='ifo_quarentine_released',
            field=models.BooleanField(default=False, verbose_name='Liberação da Quarentena IFO'),
        ),
        migrations.AddField(
            model_name='geneticmaterial',
            name='ifo_sent',
            field=models.BooleanField(default=False, help_text='Marque se este material foi enviado para a IFO.', verbose_name='Envio para IFO'),
        ),
        migrations.AddField(
            model_name='geneticmaterial',
            name='ifo_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio para a IFO'),
        ),
    ]
