# Generated by Django 5.2.7 on 2025-12-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0013_geneticmaterial_ifo_discarded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geneticmaterial',
            old_name='ifo_quarentine_released',
            new_name='ifo_quarantine_released',
        ),
    ]
