# Generated by Django 5.2.7 on 2025-12-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0014_rename_ifo_quarentine_released_geneticmaterial_ifo_quarantine_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Altitude (metros)'),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Marque se o material está ativo. Desmarque para exclusão lógica.', verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('num_plants', models.PositiveIntegerField(default=1, verbose_name='Número de Plantas')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='Data de Plantio')),
                ('rootstock', models.CharField(blank=True, max_length=100, verbose_name='Porta-enxerto')),
                ('genetic_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='germoplasm.geneticmaterial', verbose_name='Material Genético')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='germoplasm.location', verbose_name='Local de Plantio')),
            ],
            options={
                'verbose_name': 'Local de Plantio',
                'verbose_name_plural': 'Locais de Plantio (Onde tem)',
                'ordering': ['location', '-planting_date'],
            },
        ),
    ]
