# Generated by Django 5.2.7 on 2025-12-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germoplasm', '0015_location_altitude_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='altitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altitude (metros)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude (Decimal)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude (Decimal)'),
        ),
    ]
